on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # -
      #   name: Build multi-arch (linux/amd64,linux/arm64,linux/arm/v7)
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     platforms: linux/amd64,linux/arm64,linux/arm/v7
      #     tags: evanshortiss/httpsink:${{ github.event.release.tag_name }}
      -
        name: Build Image (linux/amd64)
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          tags: quay.io/evanshortiss/httpsink:${{ github.event.release.tag_name }}
      - 
        name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: quay.io/evanshortiss/httpsink
          tags: ${{ github.event.release.tag_name }}
          registry: quay.io
          username: evanshortiss
          password: ${{ secrets.REGISTRY_PASSWORD }}